### PR TITLE
Add Silke's changes to smd_producer from cxilv1118

### PR DESCRIPTION
**Pull request by ZryletTC**
@silkenelson PRing so that these changes are more visible. Not sure which of them should be merged if any, maybe it's all experiment specific.

### CODE REVIEW

**Comment by silkenelson** [comment]
I don't think we should be pulling this, at least not to the master. But this bring up the question again of what to do with experiment specific producer files: once a group has settled on something, it would be good to keep it _somewhere_.

**Comment by vespos** [comment]
This producer is for performance benchmarking. Perhaps we could make it as a separate producer that we can use whenever we want to test performances.
But I would also not start making new maintained producers each time we have a new small tasks (this would make maintenance very cumbersome), so I would only do this if we see a clear use case for it.

**Comment by silkenelson** [comment]
@vespos If you agree, we should likely just close this as "won't do"?

**Comment by vespos** [comment]
Yes, these changes were added in another PR in the end.

**Pull request closed without merging**
