### PR TITLE
Added epicsOncePV to smd*_producer.py.

### PR DESCRIPTION
**Pull request by mcb64**
Also fixed a few typos using "is" to compare to a non-None literal and lcls2_epicsDetector.params_as_dict to actually return the result.

### CODE REVIEW

**Comment by mcb64** [comment]
Also, added the ability to specify an alias in the epicsPV/epicsOncePV lists.  This is less important for PVs with an alias in the recorded data, but if we extend this to pull in archiver data, it would be useful to have a human-friendly name.

**Comment by vespos** [comment]
Perhaps something I am overlooking here, but isn't this using the first event for detOnce and then the event loop will start at the second event?

**Comment by silkenelson** [comment]
I also have Vincent's concern. Mike, can you check b y running over 10 events with and w/o epicsOnce and check on the fiducial-IDs in both cases? I will also try to check this with a simple example....

**Comment by mcb64** [comment]
The intention was that I am instantiating a separate event iterator to get the epicsOnce event.  So both *that* one and the main event loop one should see the first event.

That said, I haven't looked carefully at the iterator constructor, and it's not impossible that the iterator is a singleton, so I'm actually burning the first event on the epicsOnce.  I will check this tomorrow.

**Comment by mcb64** [comment]
Yeah, it's a singleton.  I'll fix this tomorrow, and you can review afterwards.

**Comment by mcb64** [comment]
OK, I'll make sure this works tomorrow. :-)

**Comment by vespos** [comment]
I think that looks good now!
The ds.event loop can indeed be a bit of a pain to work with for that reason; once you've seen an event it's gone forever!

**Comment by mcb64** [comment]
OK, one more time.  I decided we need the aliases and the PV names in LCLS2.  I've also fleshed out the mechanism for adding additional values (such as those from the archiver).

I've tested this on the commented-out lists in smd*_producer.py with the commented-out fill-in code in SmallDataUtils.py and it does what I expect... aliases and PVs go where they belong, non-existent values aren't mentioned in the hdf5 at all.

**Comment by mcb64** [comment]
> The ds.event loop can indeed be a bit of a pain to work with for that reason; once you've seen an event it's gone forever!

I have to say, I was a little surprised that when I had *two* separate iterators, moving one forward pushes the other one as well.  I can see why they did it that way, but it felt counterintuitive to me.

**Review by vespos — APPROVED** [review]
Looks good to me.
Just curious: why grabbing the UsrDataCfg in the event loop instead of at the same time as the other detectors? I don't think this changes anything at the end here, so I don't really mind

**Comment by mcb64** [comment]
Because I want to include the epicsOnce configuration in the UsrDataCfg.  Since I don't know which PVs actually exist in the data, I need to wait until we've at least partially processed the first event.

**Pull request merged**
